module.exports = [
  {
    key: process.env.TOKEN_1,
    discordID: "0",
    nameColor: "#0d0b0b",
    class: "developer",
    infiniteLevelUp: true,
    name: "unnamed#0000",
    note: "note here",
  },
  {
    key: process.env.TOKEN_2,
    discordID: "0",
    nameColor: "#ffffff",
    class: "developer",
    infiniteLevelUp: true,
    name: "unnamed#0000",
    note: "note here",
  },
  {
    key: process.env.TOKEN_3,
    discordID: "0",
    nameColor: "#ffffff",
    class: "developer",
    infiniteLevelUp: true,
    name: "unnamed#0000",
    modCommands: true,
    note: "note here",
  },
  {
    key: process.env.TOKEN_4,
    discordID: "0",
    nameColor: "#9e0bd1",
    class: "developer",
    administrator: true,
    bypassChatSanitizer: true,
    tesseractCommands: true,
    balancerCommands: true,
    ownerCommands: true,
    miscCommands: true,
    evalCommand: true,
    editCommand: true,
    modCommands: true,
    infiniteConnections: true,
    infiniteLevelUp: true,
    allowSpam: true,
  },
];
